#!/usr/bin/perl -w

use strict;

use Carp;

print "// Generated by $0\n\n";

while (my $line = <>) {
    chomp $line;

    next if $line !~ /^    D\((.*?)\);$/;
    my $port = $1;

    $line = <>;
    chomp $line;

#    croak if $line !~ /^\s+[0-9a-f]+:\s+[0-9a-f][0-9a-f] [0-9a-f][0-9a-f]\tldi\tr\d+, (0x[0-9a-f]+)\t;/;
    croak if $line !~ /ldi\tr\d+, (0x[0-9a-f]+)\t;/;
    print "#define N$port $1\n";
}
